'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.


'''

even_fib = 0
x1 = 0
x2 = 1
for x in range(0, 32):
    fib = x1 + x2
    x1 = x2
    x2 = fib
    # print(fib)
    if fib > 4000000:
        break
    if fib % 2 == 0:
        even_fib += fib

print(even_fib)


